config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks",
  }

  #ゲストログイン用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  devise_for :admins, controllers: {
    sessions: "admins/sessions",
    passwords: "admins/passwords",
    registrations: "admins/registrations",
  }

  #ルーティングエラー対策
  get "admins" => "admins/users#admins"

  scope module: :public do
    root to: "homes#top"
    get "/help" => "homes#help"
    get "/home" => "homes#home"
    get "/search" => "homes#search"
    get "/rank/" => "ranks#rank"

    get "unsubscribe/:name" => "homes#unsubscribe", as: "confirm_unsubscribe"
    patch ":id/withdraw/:name" => "homes#withdraw", as: "withdraw_user"
    put "withdraw/:name" => "users#withdraw"

    resources :notifications, only: [:index]

    resources :articles do
      resource :bookmarks, only: [:show, :create, :destroy]
      resources :comments, only: [:create, :destroy]
      get "/user/:id" => "articles#user_articles", as: "index"
      patch :update_status
    end
    post "articles/new" => "articles#new", as: "article_new"

    resources :users, only: [:index, :show, :edit, :update] do
      member do
          get :following, :followers
      end
    end
    resources:relationships, only: [:create, :destroy]
  end

  namespace :admins do
    resources :users, except: [:new, :create]
  end

end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:twitter], :authentication_keys => [:nickname]

  # 各モデルとのアソシエーション
  has_many :articles, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_notifications, class_name: "Notification", foreign_key: "visitor_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship",  dependent: :destroy
  has_many :following, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  # フォローするときのメソッド
  def follow(user)
    following_relationships.create!(following_id: user.id)
  end

  # フォローを外すメソッド
  def unfollow(user)
    following_relationships.find_by(following_id: user.id).destroy
  end
  
  # 既にフォロー済かどうか確認するメソッド
  def following?(user)
    following_relationships.find_by(following_id: user.id)
  end

  # SNS認証時に使用
  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    user ||= User.create(
      uid: auth.uid,
      provider: auth.provider,
      name: auth.info.name,
      nickname: auth.info.nickname,
      email: User.dummy_email(auth),
      password: Devise.friendly_token[0, 20]
    )

    user
  end

  # プロフィール画像
  attachment :profile_image

  # 退会したユーザーの再ログインを防止
  def active_for_authentication?
    super && (is_valid == true)
  end

  # ゲストログインの設定
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.nickname = "guest"
      user.name = "guest"
      user.password = SecureRandom.urlsafe_base64
    end
  end

  # バリデーション
  validates :name, presence: true, length: { in: 2..10 }, uniqueness: { case_sensitive: false }
  validates :nickname, presence: true, length: { in: 2..10 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, { presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false } }

  private

  # SNS認証
  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :edit, :admins]
  before_action :set_user, except: [:index, :admins]
  before_action :correct_user, only: [:edit, :update]

  def admins
    redirect_to new_admin_registration_path
  end

  def index
    @users = User.all.page(params[:page]).per(10)
  end

  def show
    @articles = @user.articles.page(params[:page]).per(5)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:profile_image, :name, :nickname, :introduction, :email)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user) unless @user == current_user
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  def failure
    redirect_to root_url
  end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  def twitter
    @user = User.find_for_oauth(request.env['omniauth.auth'])
    if @user
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
    else
      if (data = request.env['omniauth.auth'])
        session['devise.omniauth_data'] = {
          email: data['info']['email'],
          provider: data['provider'],
          uid: data['uid'],
        }
      end
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :ensure_normal_user, only: :create

  def ensure_normal_user
    if params[:user][:email].downcase == 'guest@example.com'
      redirect_to new_user_session_path, alert: 'ゲストユーザーのパスワード再設定はできません。'
    end
  end

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :ensure_normal_user, only: %i(update destroy)

  def ensure_normal_user
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの更新・削除はできません。'
    end
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_user, only: [:create]

  # GET /resource/sign_in
  def new
    session.delete('devise.omniauth_data')
    super
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def new_guest
    user = User.guest
    sign_in user
    redirect_to home_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.

  # 退会後のログインを阻止
  def reject_user
    @user = User.find_by(nickname: params[:user][:nickname])
    if @user
      if @user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false)
        flash[:error] = "退会済みです。"
        redirect_to new_user_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/views/admins/users/edit.html.erb
<div class = "container">
  <div class = "title text-center">
    <div>
      <%= attachment_image_tag @user, :profile_image, fallback: "no-image.png", size:'55x55', class: "rounded-circle"%>
      <%= @user.nickname %> プロフィール編集
    </div>
  </div>
  <div class = "card">
    <div class ="row justify-content-center">
      <div class = "col-8">
        <%= form_with model: @user, local:true do |f| %>
          <h6 class = "text-muted pb-1 pt-3">画像</h5>
          <%= f.attachment_field :profile_image %>

          <h6 class = "text-muted pb-1 pt-3">名前</h5>
          <%= f.text_field :name, class: "form-control" %>

          <h6 class = "text-muted pb-1 pt-3">ニックネーム</h5>
          <%= f.text_field :nickname, class: "form-control" %>

          <h6 class = "text-muted pb-1 pt-3">自己紹介</h5>
          <%= f.text_area :introduction, class: "form-control" %>

           <div class = "pb-1 pt-3">
            <%= f.submit "更新", class: "btn btn-secondary bg-secondary text-white" %>
           </div>
         <% end %>
         <div class = "float-right">
           <div><%= link_to "退会をご希望の方はこちら", confirm_unsubscribe_path(@user), class: "link mr-2" %></div>
         </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/users/index.html.erb
<div class = "container">
  <div class = "title text-center">ユーザー</div>
  <table class = "table table-bordered">
    <thead>
      <tr>
        <th>ユーザーID</th>
        <th>ユーザー名</th>
        <th>メールアドレス</th>
        <th>退会ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= link_to user.name, admins_user_path(user) %></td>
        <td><%= user.email %></td>
        <td>
          <% if user.is_valid == true %>
            <p>退会</p>
          <% else %>
            <p>有効</p>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div class = "py-3">
    <%= paginate @users %>
  </div>
</div>

app/views/admins/users/show.html.erb
<div class = "container">
  <% if @user == current_user %>
     <div class = "title text-center">マイページ</div>
  <% else %>
    <div class = "title text-center"><%= @user.nickname %>さんのマイページ</div>
  <% end %>
  
  <div class = "card">
    <div class = "text-center">
      <div class = "my-3"><%= attachment_image_tag @user, :profile_image, fallback: "no-image.png", size:'200x200', class: "rounded-circle"%></div>
      <div class = "user-nickname"><%= @user.nickname %></div>
      <div class = "info-border"></div>
      <div class = "d-flex justify-content-around ml-4 pb-3">
        <div class= "user-box">
          <div><%= @user.articles.count %></div>
          <div class = "text-muted">投稿数</div>
        </div>
        <div class = "user-box">
          <div><%= link_to @user.followings.count, user_followings_path(@user.id), class: "link" %></div>
          <div class = "text-muted">フォロー</div>
        </div>
        <div class = "user-box">
          <div><%= link_to @user.followers.count, user_followers_path(@user.id), class: "link"  %></div>
          <div class = "text-muted">フォロワー</div>
          </div>
      </div>
      <div class = "my-3 user-text"><%= @user.introduction %></div>
      <div>
        <div class = "py-2">
          <%= link_to "プロフィールを編集する", edit_user_path(@user) , class:"btn btn-outline-secondary btn-block"%>
        </div>
        <div class = "py-2">
          <%= link_to "ブックマークした投稿はこちら", article_bookmarks_path(@user.id) , class:"btn btn-outline-secondary btn-block"%>
        </div>
      </div>
    </div>
  </div>
  <div class = "sub_title text-center py-4">投稿一覧</div>
  <div class = "row">
    <div class = "col-2"></div>
    <div class = "col-8">
      <% @articles.each do |article| %>
        <%= render "public/articles/index", article: article %>
      <% end %>
      <div class = "pagination-sm pt-3">
        <%= paginate @articles %>
      </div>
    </div>
  </div>
</div>