config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks",
  }

  #ゲストログイン用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  devise_for :admins, controllers: {
    sessions: "admins/sessions",
    passwords: "admins/passwords",
    registrations: "admins/registrations",
  }

  #ルーティングエラー対策
  get "admins" => "admins/users#admins"

  scope module: :public do
    root to: "homes#top"
    get "/help" => "homes#help"
    get "/home" => "homes#home"
    get "/search" => "homes#search"
    get "/rank/" => "ranks#rank"

    get "unsubscribe/:name" => "homes#unsubscribe", as: "confirm_unsubscribe"
    patch ":id/withdraw/:name" => "homes#withdraw", as: "withdraw_user"
    put "withdraw/:name" => "users#withdraw"

    resources :notifications, only: [:index]

    resources :articles do
      resource :bookmarks, only: [:show, :create, :destroy]
      resources :comments, only: [:create, :destroy]
      get "/user/:id" => "articles#user_articles", as: "index"
      patch :update_status
    end
    post "articles/new" => "articles#new", as: "article_new"

    resources :users, only: [:index, :show, :edit, :update] do
      member do
          get :following, :followers
      end
    end
    resources:relationships, only: [:create, :destroy]
  end

  namespace :admins do
    resources :users, except: [:new, :create]
  end

end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul class = "text-danger">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
    <footer class="text-center fixed-bottom navbar-light bg-light">
      ©︎TeachMarket
    </footer>

app/views/layouts/_header.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-light">

  <div class="pl-3">
    <% if user_signed_in? %>
      <%= link_to "TeachMarket", home_path, class: "navbar-brand" %>
    <% else %>
      <%= link_to "TeachMarket", root_path, class: "navbar-brand" %>
    <% end %>
  </div>

    <% if user_signed_in? %>
      <!--検索フォーム-->
      <%= render "public/homes/search" %>

      <!--通知アイコン-->
      <%= render "public/notifications/circle" %>

      <div class="hamburger">
        <span></span>
        <span></span>
        <span></span>
      </div>

      <nav class="globalMenuSp">
        <ul>
          <li><%= link_to " マイページ", user_path(current_user), class: "far fa-user mr-2 " %></li>
          <li><%= link_to " アウトプット", new_article_path, class: "fas fa-pencil-alt" %></li>
          <li><%= link_to " アプリの使い方", help_path, class: "far fa-question-circle " %></li>
          <li><%= link_to " ログアウト", destroy_user_session_path, method: :delete, class: "fas fa-door-open" %></li>
        </ul>
      </nav>

    <% elsif admin_signed_in? %>

      <div class="hamburger">
        <span></span>
        <span></span>
        <span></span>
      </div>

      <nav class="globalMenuSp">
        <ul>
          <li><%= link_to " ログアウト", destroy_admin_session_path, method: :delete, class: "fas fa-door-open" %></li>
        </ul>
      </nav>

    <% else %>

      <div class="hamburger">
        <span></span>
        <span></span>
        <span></span>
      </div>

      <nav class="globalMenuSp">
        <ul>
          <li><%= link_to " 新規会員登録", new_user_registration_path, class: "fas fa-user-plus" %></li>
          <li><%= link_to " ログイン", new_user_session_path, class: "fas fa-sign-in-alt" %></li>
          <li><%= link_to " ゲストログイン", users_guest_sign_in_path, method: :post, class: "fas fa-users" %></li>
          <li><%= link_to " アプリの使い方", help_path, class: "nav-link far fa-question-circle" %></li>
        </ul>
      </nav>
   <% end %>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>TeachMarket</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--レシポンシブ対応-->
    <meta name="viewport" content="width=device-width,initial-scale=1.0">

    <!--CSSを読み込む-->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!--javascriptを読み込む-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--Markdownで使用-->
    <script src='https://cdnjs.cloudflare.com/ajax/libs/marked/2.0.1/marked.js'></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.6.0/styles/monokai-sublime.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.6.0/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>

     <!--FontAwesomeを読み込む-->
    <script src="https://kit.fontawesome.com/f03fd448b3.js" crossorigin="anonymous"></script>

    <!--Fontを読み込む-->
    <style>@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap');</style>

    <!--favicon設定-->
     <%= favicon_link_tag('favicon.ico') %>
  </head>

  <body>

    <%= render "layouts/header" %>

    <div class = "notifications">
      <% if flash[:notice] %>
        <p class = "notice"><%= flash[:notice] %></p>
      <% elsif flash[:alert] %>
        <p class = "alert"><%= flash[:alert] %></p>
      <% else %>
      <% end %>
    </div>

    <main>
       <%= yield %>
    </main>

    <% if user_signed_in? %>
      <div class="post_btn">
      <%= link_to new_article_path do %>
        <span class="fa-stack">
          <i class="fas fa-circle fa-stack-2x " style="color:black;"></i>
          <i class="fas fas fa-pen fa-stack-1x fa-inverse"></i>
        </span>
      <% end %>
      </div>
    <% end %>

    <span id="back">
      <a href="">
        <%= image_tag asset_path("arrow.png"), data: {"turbolinks"=>false}, class: "arrow" %>
      </a>
    </span>

    <%= render "layouts/footer" %>

    <script>
      $(document).on("turbolinks:load", function() {
      $('div.rate').empty();
      $('div.rate').raty({
          size: 14,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          half: true,
          readOnly: true,
        });
      });
    </script>

  </body>
</html>